### ISSUE TITLE
Disable 2FA

### ISSUE THREAD

**Issue by tellco-nor** [nemerald-voip/laravel-freeswitch#11]
I seem to have it installed. However, I cannot seem to get the e-mail to work for 2FA. Is there a way to disable 2FA?

**Comment by nemerald-voip** [comment]
try commenting out email-challenge in fortify.php 

```
    'features' => [
        // Features::registration(),
        Features::resetPasswords(),
        // Features::emailVerification(),
        Features::updateProfileInformation(),
        Features::updatePasswords(),
        Features::twoFactorAuthentication([
            'confirm' => true,
            'confirmPassword' => true,
            // 'window' => 5,
        ]),
        // 'email-challenge',
        'remember-cookie',
    ],
```

The email settings are configured in the .env file. You can follow the Laravel official documentation to set up your email server.

**Comment by nemerald-voip** [comment]
Follow full installation tutorial and you will not have this issue

https://youtu.be/7v8sepsqnH4

@tellco-nor

**Comment by nemerald-voip** [comment]
Closing as resolved
